### ISSUE TITLE
MailSummary fails in production

### ISSUE THREAD

**Issue by andythigpen** [andythigpen/Review#83]
default from doesn't seem to work:

{A sender (Return-Path, Sender or From) required to send a message
/var/lib/gems/1.8/gems/mail-2.3.2/lib/mail/network/delivery_methods/smtp.rb:97:in `deliver!'
/var/lib/gems/1.8/gems/mail-2.3.2/lib/mail/message.rb:1989:in`do_delivery'
/var/lib/gems/1.8/gems/mail-2.3.2/lib/mail/message.rb:230:in `deliver'
/var/lib/gems/1.8/gems/actionmailer-3.1.4/lib/action_mailer/base.rb:432:in`deliver_mail'
/var/lib/gems/1.8/gems/activesupport-3.1.4/lib/active_support/notifications.rb:53:in `instrument'
/var/lib/gems/1.8/gems/activesupport-3.1.4/lib/active_support/notifications/instrumenter.rb:21:in`instrument'
/var/lib/gems/1.8/gems/activesupport-3.1.4/lib/active_support/notifications.rb:53:in `instrument'
/var/lib/gems/1.8/gems/actionmailer-3.1.4/lib/action_mailer/base.rb:430:in`deliver_mail'
/var/lib/gems/1.8/gems/mail-2.3.2/lib/mail/message.rb:230:in `deliver'
/home/review/Review/lib/mail_summary_job.rb:12:in`perform'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/backend/base.rb:94:in `invoke_job'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:60:in`call'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:60:in `initialize'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:65:in`call'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:65:in `execute'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:38:in`run_callbacks'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/backend/base.rb:91:in `invoke_job'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/worker.rb:162:in`run'
/usr/lib/ruby/1.8/timeout.rb:67:in `timeout'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/worker.rb:162:in`run'
/usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/worker.rb:161:in`run'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/worker.rb:218:in `reserve_and_run_one_job'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:60:in`call'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:60:in `initialize'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:65:in`call'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:65:in `execute'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:38:in`run_callbacks'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/worker.rb:218:in `reserve_and_run_one_job'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/worker.rb:146:in`work_off'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/worker.rb:145:in `times'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/worker.rb:145:in`work_off'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/worker.rb:117:in `start'
/usr/lib/ruby/1.8/benchmark.rb:308:in`realtime'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/worker.rb:116:in `start'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:60:in`call'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:60:in `initialize'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:65:in`call'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:65:in `execute'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:38:in`run_callbacks'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/worker.rb:113:in `start'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/worker.rb:112:in`loop'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/worker.rb:112:in `start'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/plugins/clear_locks.rb:7:in`call'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/plugins/clear_locks.rb:7
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:78:in `call'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:78:in`add'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:60:in `call'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:60:in`initialize'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:78:in `call'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:78:in`add'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:65:in `call'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:65:in`execute'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/worker.rb:111:in`start'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/command.rb:98:in `run'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/command.rb:86:in`run_process'
/var/lib/gems/1.8/gems/daemons-1.1.8/lib/daemons/application.rb:254:in `call'
/var/lib/gems/1.8/gems/daemons-1.1.8/lib/daemons/application.rb:254:in`start_proc'
/var/lib/gems/1.8/gems/daemons-1.1.8/lib/daemons/daemonize.rb:79:in `call'
/var/lib/gems/1.8/gems/daemons-1.1.8/lib/daemons/daemonize.rb:79:in`call_as_daemon'
/var/lib/gems/1.8/gems/daemons-1.1.8/lib/daemons/application.rb:258:in `start_proc'
/var/lib/gems/1.8/gems/daemons-1.1.8/lib/daemons/application.rb:295:in`start'
/var/lib/gems/1.8/gems/daemons-1.1.8/lib/daemons/application_group.rb:159:in `start_all'
/var/lib/gems/1.8/gems/daemons-1.1.8/lib/daemons/application_group.rb:158:in`fork'
/var/lib/gems/1.8/gems/daemons-1.1.8/lib/daemons/application_group.rb:158:in `start_all'
/var/lib/gems/1.8/gems/daemons-1.1.8/lib/daemons/application_group.rb:157:in`each'
/var/lib/gems/1.8/gems/daemons-1.1.8/lib/daemons/application_group.rb:157:in `start_all'
/var/lib/gems/1.8/gems/daemons-1.1.8/lib/daemons/controller.rb:80:in`run'
/var/lib/gems/1.8/gems/daemons-1.1.8/lib/daemons.rb:197:in `run_proc'
/var/lib/gems/1.8/gems/daemons-1.1.8/lib/daemons/cmdline.rb:109:in`call'
/var/lib/gems/1.8/gems/daemons-1.1.8/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/var/lib/gems/1.8/gems/daemons-1.1.8/lib/daemons.rb:196:in`run_proc'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/command.rb:84:in `run_process'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/command.rb:77:in`daemonize'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/command.rb:75:in `times'
/var/lib/gems/1.8/gems/delayed_job-3.0.1/lib/delayed/command.rb:75:in`daemonize'
script/delayed_job:5

**Comment by andythigpen** [comment]
Comment MailSummary still fails when @comments.size == 0
